#!/bin/bash

# Define an array of packages to check and install
# pacman_pkg=("git" "hyprland" "noto-fonts" "noto-fonts-cjk" "noto-fonts-emoji" "ttf-firacode-nerd" "otf-font-awesome" "kitty" "starship" "hyprpaper" "ranger" "feh" "mpv" "udisks2" "grim" "slurp" "wl-clipboard" "mako" "pipewire" "wireplumber" "xdg-desktop-portal-hyprland" "qt5-wayland" "qt6-wayland" "polkit-kde-agent" "udiskie" "lightdm" "lightdm-gtk-greeter" "gtk3" "qt5ct" "lxappearance" "gnome-themes-extra")
#
# # Loop through the array
# for package in "${pacman_pkg[@]}"; do
#     # Check if the package is installed
#     if pacman -Q "$package" &>/dev/null; then
#         echo "'$package' is already installed"
#     else
#         # Install the package using pacman -S
#         echo "Installing '$package'..."
#         sudo pacman -S "$package"
#         if [ "$package" == "networkmanager" ]; then
#             echo "Configuring NetworkManager..."
#             sudo systemctl enable NetworkManager.service
#         fi
#         if [ "$package" == "lightdm" ]; then
#             echo "Configuring lightdm..."
#             sudo systemctl enable lightdm.service
#         fi
#     fi
# done

# Check if rustup is already installed
if command -v rustup &>/dev/null; then
    echo "Rust is already installed."
else
    # Download and run the rustup installer script
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

    # Add rust to the current shell session
    . $HOME/.cargo/env
fi

# Check if binstall is already installed
if command -v cargo-binstall &>/dev/null; then
    echo "cargo-binstall is already installed."
else
    curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
fi

# Define an array of packages to check and install
packages=("rtx-cli" "alacritty" "exa" "zellij" "bacon" "bat" "dezoomify-rs" "grex" "sqlx-cli" "ytop" "xh" "mprocs" "irust" "du-dust" "fd-find" "inlyne" "miniserve" "procs" "tealdeer" "rm-improved" "hx" "cfonts" "himalaya")

for package in "${packages[@]}"; do
    # Check if the package is installed
    if command -v "$package" &>/dev/null; then
        echo "'$package' is already installed"
    else
        # Download and install the package
        echo "Installing '$package'..."
        cargo binstall "$package"
    fi
done

# Check if bun is already installed
if command -v bun &>/dev/null; then
    echo "bun is already installed."
else
    # Download and run the bun installer script
    curl -fsSL https://bun.sh/install | bash
fi

rtx_pkg=("node" "dotnet" "java" "go" "python" "neovim")

for package in "${rtx_pkg[@]}"; do
    # Download and install the package
    echo "Installing '$package'..."
    rtx install "$package"
    rtx use -g "$package"
done

# Add dotfile bare git repo
echo ".dotfiles" >> .gitignore
git clone --bare https://github.com/grepvenancio/dotfiles.git $HOME/.dotfiles

# Check if nvim is already Installed
if command -v bun &>/dev/null; then
    echo "neovim is already installed."
else
    cd "/tmp"
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    chmod u+x nvim.appimage
    ./nvim.appimage --appimage-extract
    ./squashfs-root/AppRun --version
    sudo mv squashfs-root /
    sudo ln -s /squashfs-root/AppRun /usr/bin/nvim
fi
